/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractProjectDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProjectDSLRuntimeModule extends AbstractProjectDSLRuntimeModule {
}
