/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectDSLStandaloneSetup extends ProjectDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
