/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.projectdsl.ui.internal.ProjectdslActivator;

public class ProjectDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjectdslActivator.getInstance().getInjector("org.xtext.example.mydsl.ProjectDSL");
	}

}
