/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.ProjectDSLRuntimeModule;
import org.xtext.example.mydsl.ProjectDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ProjectDSLIdeSetup extends ProjectDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProjectDSLRuntimeModule(), new ProjectDSLIdeModule()));
	}
	
}
