/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.projectDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Div</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.projectDSL.ProjectDSLPackage#getDiv()
 * @model
 * @generated
 */
public interface Div extends Expression
{
} // Div
