/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.projectDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.projectDSL.ProjectDSLPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends Expression
{
} // Mult
