/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.projectDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.projectDSL.Param#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.projectDSL.ProjectDSLPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Parameter)
   * @see org.xtext.example.mydsl.projectDSL.ProjectDSLPackage#getParam_Value()
   * @model
   * @generated
   */
  Parameter getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.projectDSL.Param#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Parameter value);

} // Param
