/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.projectDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.projectDSL.ProjectDSLFactory
 * @model kind="package"
 * @generated
 */
public interface ProjectDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "projectDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/ProjectDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "projectDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectDSLPackage eINSTANCE = org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.RestAPIImpl <em>Rest API</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.RestAPIImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getRestAPI()
   * @generated
   */
  int REST_API = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Rest API</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_API_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.DeclarationImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.EntityImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Ctrlr</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__CTRLR = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__PARAMETERS = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.ControllerImpl <em>Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.ControllerImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getController()
   * @generated
   */
  int CONTROLLER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__NAME = DECLARATION__NAME;

  /**
   * The feature id for the '<em><b>Base</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__BASE = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Endpoint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__ENDPOINT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.EndpointImpl <em>Endpoint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.EndpointImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getEndpoint()
   * @generated
   */
  int ENDPOINT = 4;

  /**
   * The feature id for the '<em><b>Endpoint</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDPOINT__ENDPOINT = 0;

  /**
   * The number of structural features of the '<em>Endpoint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENDPOINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.ParameterImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__DATA_TYPE = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 2;

  /**
   * The feature id for the '<em><b>Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__BASE = 3;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.projectDSL.impl.RedirectImpl <em>Redirect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.projectDSL.impl.RedirectImpl
   * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getRedirect()
   * @generated
   */
  int REDIRECT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDIRECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDIRECT__URL = 1;

  /**
   * The number of structural features of the '<em>Redirect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDIRECT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.RestAPI <em>Rest API</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest API</em>'.
   * @see org.xtext.example.mydsl.projectDSL.RestAPI
   * @generated
   */
  EClass getRestAPI();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.projectDSL.RestAPI#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.projectDSL.RestAPI#getName()
   * @see #getRestAPI()
   * @generated
   */
  EAttribute getRestAPI_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.projectDSL.RestAPI#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.example.mydsl.projectDSL.RestAPI#getDeclarations()
   * @see #getRestAPI()
   * @generated
   */
  EReference getRestAPI_Declarations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.projectDSL.Declaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Declaration#getName()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.projectDSL.Entity#getCtrlr <em>Ctrlr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ctrlr</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Entity#getCtrlr()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Ctrlr();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.projectDSL.Entity#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Entity#getParameters()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Controller <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Controller</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Controller
   * @generated
   */
  EClass getController();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.projectDSL.Controller#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Base</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Controller#getBase()
   * @see #getController()
   * @generated
   */
  EReference getController_Base();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.projectDSL.Controller#getEndpoint <em>Endpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Endpoint</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Controller#getEndpoint()
   * @see #getController()
   * @generated
   */
  EReference getController_Endpoint();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Endpoint <em>Endpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Endpoint</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Endpoint
   * @generated
   */
  EClass getEndpoint();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.projectDSL.Endpoint#getEndpoint <em>Endpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Endpoint</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Endpoint#getEndpoint()
   * @see #getEndpoint()
   * @generated
   */
  EReference getEndpoint_Endpoint();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.projectDSL.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.projectDSL.Parameter#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Parameter#getDataType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_DataType();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.projectDSL.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Type</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.projectDSL.Parameter#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Base</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Parameter#getBase()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Base();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.projectDSL.Redirect <em>Redirect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Redirect</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Redirect
   * @generated
   */
  EClass getRedirect();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.projectDSL.Redirect#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Redirect#getName()
   * @see #getRedirect()
   * @generated
   */
  EReference getRedirect_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.projectDSL.Redirect#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.projectDSL.Redirect#getUrl()
   * @see #getRedirect()
   * @generated
   */
  EAttribute getRedirect_Url();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProjectDSLFactory getProjectDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.RestAPIImpl <em>Rest API</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.RestAPIImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getRestAPI()
     * @generated
     */
    EClass REST_API = eINSTANCE.getRestAPI();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST_API__NAME = eINSTANCE.getRestAPI_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST_API__DECLARATIONS = eINSTANCE.getRestAPI_Declarations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.DeclarationImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__NAME = eINSTANCE.getDeclaration_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.EntityImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Ctrlr</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__CTRLR = eINSTANCE.getEntity_Ctrlr();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__PARAMETERS = eINSTANCE.getEntity_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.ControllerImpl <em>Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.ControllerImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getController()
     * @generated
     */
    EClass CONTROLLER = eINSTANCE.getController();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__BASE = eINSTANCE.getController_Base();

    /**
     * The meta object literal for the '<em><b>Endpoint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__ENDPOINT = eINSTANCE.getController_Endpoint();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.EndpointImpl <em>Endpoint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.EndpointImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getEndpoint()
     * @generated
     */
    EClass ENDPOINT = eINSTANCE.getEndpoint();

    /**
     * The meta object literal for the '<em><b>Endpoint</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENDPOINT__ENDPOINT = eINSTANCE.getEndpoint_Endpoint();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.ParameterImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__DATA_TYPE = eINSTANCE.getParameter_DataType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__BASE = eINSTANCE.getParameter_Base();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.projectDSL.impl.RedirectImpl <em>Redirect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.projectDSL.impl.RedirectImpl
     * @see org.xtext.example.mydsl.projectDSL.impl.ProjectDSLPackageImpl#getRedirect()
     * @generated
     */
    EClass REDIRECT = eINSTANCE.getRedirect();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REDIRECT__NAME = eINSTANCE.getRedirect_Name();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REDIRECT__URL = eINSTANCE.getRedirect_Url();

  }

} //ProjectDSLPackage
