/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ProjectDSLUiModule extends AbstractProjectDSLUiModule {
  public ProjectDSLUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe type ProjectDSLUiModule is already defined in ProjectDSLUiModule.java.");
  }
}
