/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.validation;

import com.google.common.base.Objects;
import java.util.ArrayList;
import java.util.function.Consumer;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.xtext.example.mydsl.projectDSL.Controller;
import org.xtext.example.mydsl.projectDSL.Endpoint;
import org.xtext.example.mydsl.projectDSL.Entity;
import org.xtext.example.mydsl.projectDSL.Parameter;
import org.xtext.example.mydsl.projectDSL.ProjectDSLPackage;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ProjectDSLValidator extends AbstractProjectDSLValidator {
  @Check
  public void checkMakeOperations(final Controller c) {
    final ArrayList<String> endpointNames = new ArrayList<String>();
    final Consumer<Endpoint> _function = (Endpoint it) -> {
      boolean _contains = endpointNames.contains(it.getEndpoint().getName());
      if (_contains) {
        this.error("Endpoint already exists!", it, ProjectDSLPackage.Literals.ENDPOINT__ENDPOINT);
      } else {
        endpointNames.add(it.getEndpoint().getName());
      }
    };
    c.getEndpoint().forEach(_function);
  }
  
  @Check
  public void checkCRUDNames(final Entity e) {
    final ArrayList<String> entityParameterNames = new ArrayList<String>();
    final Consumer<Parameter> _function = (Parameter it) -> {
      boolean _contains = entityParameterNames.contains(it.getName());
      if (_contains) {
        this.error("Parameter already exists!", it, ProjectDSLPackage.Literals.PARAMETER__NAME);
      } else {
        entityParameterNames.add(it.getName());
      }
    };
    e.getParameters().forEach(_function);
  }
  
  @Check
  public void checkCRUDParameters(final Parameter parameter) {
    for (int i = 0; (i < ((Object[])Conversions.unwrapArray(parameter.getType(), Object.class)).length); i++) {
      for (int j = 0; (j < ((Object[])Conversions.unwrapArray(parameter.getType(), Object.class)).length); j++) {
        if (((i != j) && Objects.equal(parameter.getType().get(i), parameter.getType().get(j)))) {
          String _get = parameter.getType().get(i);
          String _plus = ("Parameters contains duplicates of " + _get);
          this.error(_plus, parameter, ProjectDSLPackage.Literals.PARAMETER__NAME);
        }
      }
    }
  }
}
