/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.ProjectDSLRuntimeModule;
import org.xtext.example.mydsl.ProjectDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ProjectDSLIdeSetup extends ProjectDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ProjectDSLRuntimeModule _projectDSLRuntimeModule = new ProjectDSLRuntimeModule();
    ProjectDSLIdeModule _projectDSLIdeModule = new ProjectDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_projectDSLRuntimeModule, _projectDSLIdeModule));
  }
}
