/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractProjectDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProjectDSLIdeModule extends AbstractProjectDSLIdeModule {
}
